[package]
name = "spaniel"
version = "0.1.0"
authors = ["Johan Mickos <johanmi@kth.se>"]

[dependencies]
bytes = "0.4.7"
byteorder = "1.1"
futures = "0.1.21"

tokio-tcp = "0.1.0"
tokio-executor = "0.1.2"
tokio-threadpool = "0.1.2"
tokio-io = "0.1.6"
tokio-timer = "0.2.3"
