[package]
name = "spaniel"
version = "0.1.0"
authors = ["Johan Mickos <johanmi@kth.se>"]

[dependencies]
bytes = "0.4.8"
byteorder = "1.1"
futures = "0.1.21"

[dependencies.tokio-io]
git = "https://github.com/jarlopez/tokio"
branch = "bytes-v0.4.8-migration"
path = "tokio-io"
